#!/bin/bash

# check for backup directory
# if /var/backup exists then move to dir and run log backup
# else create dir then move to dir and run backup

if [ -d /var/backup ]; then
	cd /var/backup
	
	tar czf logs_archive_$(hostname)_$(date +%Y-%m-%d_%H-%M-%S).tar.gz $1  
else
	mkdir /var/backup
	cd /var/backup
	tar czf logs_archive_$(hostname)_$(date +%Y-%m-%d_%H-%M-%S).tar.gz $1  
fi
